services:

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - "./ollama/:/root/.ollama"

    # nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
