import os
import sys
import glob

import util

input_path = sys.argv[1]
input_path = os.path.abspath(input_path)

if not os.path.isdir(input_path):
    print("DIRECOTRY NOT FOUND")
    sys.exit()

print("PROJECT DIRECTORY LOADED: ", input_path)

content = glob.glob(input_path)

docker_yaml = ''
docker_yaml += "# Generated by raven cli tool build by raxen and vasanth"
docker_yaml += "\n"
docker_yaml += util.gen_yaml(str(content))

print(docker_yaml)

docker_path = os.path.join(input_path, "docker-compose.yml")

try:
    with open(docker_path, 'x') as docker_file:
        docker_file.write(docker_yaml)
except FileExistsError:
    with open(docker_path, 'w') as docker_file:
        docker_file.write(docker_yaml)



